server:
  port: 9898

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://:3306/scoreDB?useUnicode=true&characterEncoding=utf-8

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 3000
      pool-prepared-statements: false
      max-open-prepared-statements: -1
      time-between-eviction-runs-millis: 60000
      max-evictable-idle-time-millis: 400000
      min-evictable-idle-time-millis: 300000

      filters: stat,wall
      aop-patterns: cn.redarm.trainingtest1.*

      web-stat-filter:
        enabled: true
        url-pattern: /*

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid
        allow: 127.0.0.1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  redis:
    port: 6379
    password:
    host:
  mail:
    username:
    password:
    host: smtp.qq.com
    properties.mail.smtp.ssl.enable: true

logging:
  file:
    path: ${user.home}/.scoreManager/logs
  level:
    cn.redarm.studentscoremanager: warn

jwt:
  secret: redarm
  expireTime: 86400

redis:
  key:
    expireTime: 120

jasypt:
  encryptor:
    password: redarm
    property:
      prefix: Redarm(
      suffix: )

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
